export const FETCH_ESTABLISHMENTS_REQUEST = 'FETCH_ESTABLISHMENTS_REQUEST';
export const FETCH_ESTABLISHMENTS_SUCCESS = 'FETCH_ESTABLISHMENTS_SUCCESS';
export const FETCH_ESTABLISHMENTS_FAILURE = 'FETCH_ESTABLISHMENTS_FAILURE';


// Record action types
export const FETCH_RECORDS_REQUEST = 'FETCH_RECORDS_REQUEST';
export const FETCH_RECORDS_SUCCESS = 'FETCH_RECORDS_SUCCESS';
export const FETCH_RECORDS_FAILURE = 'FETCH_RECORDS_FAILURE';
export const ADD_RECORD = 'ADD_RECORD';
export const ADD_RECORD_FAILURE = 'ADD_RECORD_FAILURE';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const UPDATE_RECORD_FAILURE = 'UPDATE_RECORD_FAILURE';
export const DELETE_RECORD = 'DELETE_RECORD';
export const DELETE_RECORD_FAILURE = 'DELETE_RECORD_FAILURE';


// Action Types for fetching and updating reports
export const ADD_REPORT = 'ADD_REPORT';
export const UPDATE_REPORT = 'UPDATE_REPORT';
export const REMOVE_REPORT = 'REMOVE_REPORT';
export const FETCH_REPORTS_REQUEST = 'FETCH_REPORTS_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'FETCH_REPORTS_FAILURE';
export const UPDATE_REPORTS = 'UPDATE_REPORTS'; // New type for WebSocket updates
export const CLEAR_REPORTS_ERROR = 'CLEAR_REPORTS_ERROR';

export const FETCH_ESTABLISHMENT_HISTORY_REQUEST = 'FETCH_ESTABLISHMENT_HISTORY_REQUEST';
export const FETCH_ESTABLISHMENT_HISTORY_SUCCESS = 'FETCH_ESTABLISHMENT_HISTORY_SUCCESS';
export const FETCH_ESTABLISHMENT_HISTORY_FAILURE = 'FETCH_ESTABLISHMENT_HISTORY_FAILURE';

export const FETCH_SEARCH_SUGGESTIONS_REQUEST = 'FETCH_SEARCH_SUGGESTIONS_REQUEST';
export const FETCH_SEARCH_SUGGESTIONS_SUCCESS = 'FETCH_SEARCH_SUGGESTIONS_SUCCESS';
export const FETCH_SEARCH_SUGGESTIONS_FAILURE = 'FETCH_SEARCH_SUGGESTIONS_FAILURE';

// Contacts 
export const FETCH_CONTACTS_BEGIN = 'FETCH_CONTACTS_BEGIN';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';




